name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    # Run at 5:30 every day.
    - cron: '30 5 * * *'

jobs:
  build:
    # TODO: Does this make sense?
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Pip caching
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install Python dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Generate README
        run: |
          python3 build_readme.py
      - name: Commit and push if changed
        run: |
          # fuck fuck lor
          git status
          # Save the diff so we can see what changes have been made.
          git diff
          # Set info for commti
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          # Commit everything or quit
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          # Push changes
          git push
